version: "3"
services:
    node:
        image: node:16-bullseye-slim
        user: node
        container_name: node
        working_dir: /home/node/app
        volumes:
            - ./node:/home/node/app
            - ./log:/home/node/.npm
        ports:
            - 8081:8081
        expose:
            - 8081
        command: "sleep infinity"